version: "3"
services:

  db:
    image: postgres
    restart: always
    networks:
      - network1
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=demodb
    ports:
      - "5432"

  # web:
  #   build: .
  #   command: bundle exec rackup -p 3000
  #   volumes:
  #     - .:/myapp
  #   ports:
  #     - "3000:3000"